import React from 'react';
import { QRCodeSVG } from 'qrcode.react';
import { EWayBillData } from '../types';

interface Props {
  data: EWayBillData;
}

export function EWayBillTemplate({ data }: Props) {
  const isModern = data.supplier.templateStyle === 'modern';

  return (
    <div className={`bg-white shadow-2xl border border-slate-200 flex p-12 relative overflow-hidden print-area w-[210mm] max-w-[210mm] min-h-[297mm] !shadow-none !border-none !rounded-none ${isModern ? 'flex-row' : 'flex-col'}`} id="document-preview">
      {isModern ? (
        <div 
          className="absolute top-0 left-0 h-full w-4" 
          style={{ backgroundColor: data.supplier.accentColor || '#8b5cf6' }}
        ></div>
      ) : (
        <div 
          className="absolute top-0 left-0 w-full h-3" 
          style={{ backgroundColor: data.supplier.accentColor || '#8b5cf6' }}
        ></div>
      )}

      {/* Watermark */}
      <div className="absolute top-4 right-0 p-4">
        <span className="px-3 py-1 bg-green-100 text-green-700 text-[10px] font-bold rounded-full uppercase tracking-widest">Valid Document</span>
      </div>

      <div className={`flex flex-col w-full h-full ${isModern ? 'pl-4' : ''}`}>
        <div className={`flex justify-between items-start mb-10 ${isModern ? 'flex-row-reverse border-b pb-8' : ''}`}>
          <div className={`flex flex-col gap-3 ${isModern ? 'text-right items-end' : ''}`}>
            {data.supplier.logoUrl && (
              <img src={data.supplier.logoUrl} alt="Company Logo" className={`h-28 w-auto max-w-[320px] object-contain ${isModern ? 'object-right' : 'object-left'}`} />
            )}
            <h3 className="text-2xl font-serif font-bold tracking-tight" style={{ color: data.supplier.accentColor || '#0f172a' }}>E-WAY BILL</h3>
            <p className="text-slate-500 text-sm">Under rule 138 of the CGST Rules, 2017</p>
          </div>
          <div className={isModern ? 'text-left' : 'text-right'}>
            <p className="text-sm font-bold text-slate-800">#{data.ewayBillNo}</p>
            <p className="text-xs text-slate-400 mt-1">Generated: {new Date(data.date).toLocaleDateString('en-GB')}</p>
            <p className="text-xs text-slate-400 mt-1">Valid Until: {new Date(data.validUntil).toLocaleDateString('en-GB')}</p>
          </div>
        </div>

        <div className="mb-10 p-4 border border-slate-200 rounded-lg bg-slate-50">
          <h4 className="text-[10px] font-bold text-slate-400 uppercase mb-3 border-b border-slate-200 pb-2">Generated by</h4>
          <p className="text-sm font-bold text-slate-800">{data.generator}</p>
        </div>

        <div className="mb-10">
          <h2 className="text-lg font-serif font-bold pb-2 mb-6" style={{ borderBottomColor: data.supplier.accentColor || '#0f172a', borderBottomWidth: '2px', color: data.supplier.accentColor || '#0f172a' }}>PART - A</h2>
          
          <div className="grid grid-cols-2 gap-12 mb-8">
            <div>
              <h3 className="text-[10px] font-bold text-slate-400 uppercase mb-2">Supplier Details (Dispatch From)</h3>
              <p className="font-bold text-slate-800 text-sm">{data.supplier.name}</p>
              <p className="text-slate-600 text-sm mt-1">{data.dispatchFrom}</p>
              <p className="text-slate-500 text-xs mt-2">GSTIN: <span className="font-mono text-slate-700">{data.supplier.taxId}</span></p>
            </div>
            <div className="text-right">
              <h3 className="text-[10px] font-bold text-slate-400 uppercase mb-2">Recipient Details (Ship To)</h3>
              <p className="font-bold text-slate-800 text-sm">{data.recipient.name}</p>
              <p className="text-slate-600 text-sm mt-1">{data.shipTo}</p>
              <p className="text-slate-500 text-xs mt-2">GSTIN: <span className="font-mono text-slate-700">{data.recipient.taxId}</span></p>
            </div>
          </div>

          <table className="w-full text-sm">
            <thead className="border-b border-slate-300 text-left">
              <tr>
                <th className="py-2 text-slate-500 font-semibold">HSN Code</th>
                <th className="py-2 text-slate-500 font-semibold text-right">Total Invoice Value</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="py-4 font-mono text-slate-800">{data.hsnCode}</td>
                <td className="py-4 font-mono font-medium text-slate-900 text-right">GH₵{data.goodsValue.toLocaleString('en-US', {minimumFractionDigits: 2})}</td>
              </tr>
            </tbody>
          </table>
        </div>

        <div className="flex-1">
          <h2 className="text-lg font-serif font-bold pb-2 mb-6" style={{ borderBottomColor: data.supplier.accentColor || '#0f172a', borderBottomWidth: '2px', color: data.supplier.accentColor || '#0f172a' }}>PART - B</h2>
          
          <table className="w-full text-sm">
            <thead className="border-b border-slate-300 text-left">
              <tr>
                <th className="py-2 font-semibold text-slate-500">Vehicle Number</th>
                <th className="py-2 font-semibold text-slate-500">Transporter Name</th>
                <th className="py-2 font-semibold text-slate-500">Doc No & Date</th>
              </tr>
            </thead>
            <tbody>
              <tr className="border-b border-slate-100">
                <td className="py-4 font-mono font-bold text-slate-900">{data.vehicleNumber}</td>
                <td className="py-4 text-slate-800">{data.transporterName}</td>
                <td className="py-4 text-slate-800">{data.transportDocNo} <br/><span className="text-slate-400 text-xs">{new Date(data.transportDocDate).toLocaleDateString()}</span></td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div className="mt-8 border-t border-slate-200 pt-8 flex justify-between px-8 items-end">
          <div className="flex items-end gap-6 h-[120px]">
            {data.supplier.includeQrCode && (
              <div className="flex flex-col items-center gap-1 border border-slate-200 p-1.5 rounded bg-white mt-8">
                <QRCodeSVG value={`EWB:${data.ewayBillNo}|VAL:${data.goodsValue}`} size={64} />
                <span className="text-[8px] uppercase tracking-wider text-slate-400 font-bold">Scan</span>
              </div>
            )}
            <div className="text-center flex flex-col items-center justify-end w-64">
              {data.supplier.signatureUrl && (
                <img src={data.supplier.signatureUrl} className="h-28 w-full object-contain object-bottom mb-1" alt="signature" />
              )}
              <div className="w-full border-b border-slate-400 mb-2"></div>
              <p className="text-[10px] text-slate-700 uppercase tracking-widest font-bold">Authorized Signatory</p>
            </div>
          </div>
          <div className="text-center flex flex-col items-center justify-end w-64 h-[120px]">
            <div className="w-full border-b border-slate-400 mb-2"></div>
            <p className="text-[10px] text-slate-700 uppercase tracking-widest font-bold">Transporter</p>
          </div>
        </div>
      </div>
    </div>
  );
}
